Repository boostcamp-2020/IssueTracker-34, pull requests merged in 2020-11, with the labels that each got.

#81 Backend environment
  back/package-lock.json
  back/package.json
Labels: 환경 설정

#82 Frontend environment
  front/package-lock.json
  front/package.json
Labels: 환경 설정

#72 Issue list checkbox 추가
  front/src/components/IssueContent.js
  front/src/components/IssueList.js
  front/src/components/SelectedCount.js
Labels: 이슈 목록 화면

#75 Create Mark As dropdown component
  front/src/components/MarkAs.js
Labels: 이슈 목록 화면

#117 Sequelize 모델 정의 및 관계 설정
  back/src/app.js
  back/src/sequelizeModels/assignee.sequelizeModel.js
  back/src/sequelizeModels/comment.sequelizeModel.js
  back/src/sequelizeModels/config.sequelizeModels.js
  back/src/sequelizeModels/index.js
  back/src/sequelizeModels/issue.sequelizeModel.js
  back/src/sequelizeModels/issues_has_labels.sequelizeModel.js
  back/src/sequelizeModels/label.sequelizeModel.js
  back/src/sequelizeModels/milestone.sequelizeModel.js
  back/src/sequelizeModels/relationship.sequelizeModel.js
  back/src/sequelizeModels/user.sequelizeModel.js
Labels: 환경 설정

#73 FilterSearchBar onSubmit으로 변경
  front/src/components/FilterSearchBar.js
Labels: 이슈 목록 화면

#74 Issue Staus Change Button
  front/src/components/IssueStatusChangeButton.js
  front/src/components/IssueTitle.js
  front/src/pages/IssueDetailPage.js
Labels: 이슈 상세 화면

#123 Dotenv sample
  back/.env.sample
Labels: API

#79 Label Filter Button
  front/src/components/LabelFilterButton.js
Labels: 이슈 목록 화면

#80 Milestone Filter Button
  front/src/components/MilestoneFilterButton.js
Labels: 이슈 목록 화면

#118 Create comment
  back/src/controllers/comment.controller.js
  back/src/middleware/testAuth.js
  back/src/models/comment.model.js
  back/src/routes/comment.route.js
  back/src/routes/index.js
  back/src/services/comment.service.js
Labels: API

#76 Create commentWriteSection
  front/src/components/CommentWriteSection.js
Labels: 이슈 상세 화면

#119 Delete label service
  back/src/services/label.service.js
Labels: API

#120 EditLabel model
  back/src/models/label.model.js
Labels: API

#121 Create label route
  back/src/middleware/validateInputs.js
  back/src/routes/label.route.js
Labels: API

#122 GetLabel controller
  back/src/controllers/label.controller.js
Labels: API

#128 Milestone API
  back/src/controllers/milestone.controller.js
  back/src/models/milestone.model.js
  back/src/routes/milestone.route.js
  back/src/services/milestone.service.js
Labels: API

#135 Create label model
  back/src/models/label.model.js
Labels: API

#136 Label API
  back/src/controllers/label.controller.js
  back/src/models/label.model.js
  back/src/routes/label.route.js
  back/src/services/label.service.js
Labels: API

#137 Edit label service
  back/src/services/label.service.js
Labels: API

#138 Label API (createLabel controller, deleteLabel model, editLabel route, getLabels service)
  back/src/controllers/label.controller.js
  back/src/models/label.model.js
  back/src/routes/label.route.js
  back/src/services/label.service.js
Labels: API

#139 Get labels route
  back/src/routes/label.route.js
Labels: API

#140 DeleteLabelController
  back/src/controllers/label.controller.js
Labels: API

#141 Resolve Conflict (Label API)
  back/src/controllers/label.controller.js
  back/src/middleware/validateInputs.js
  back/src/models/label.model.js
  back/src/services/label.service.js
Labels: API

#124 Github Oauth
  back/package-lock.json
  back/package.json
  back/src/app.js
  back/src/middleware/passport.js
Labels: API

#129 AssigneeSelector
  front/src/components/AssigneesSelector.js
Labels: 이슈 상세 화면

#125 JWTToken
  back/src/services/jwtToken.service.js
Labels: API

#126 User API
  back/src/controllers/user.controller.js
  back/src/models/user.model.js
  back/src/routes/index.js
  back/src/routes/user.route.js
  back/src/services/user.service.js
Labels: API

#127 Token validator middleware
  back/src/middleware/tokenValidator.js
Labels: API

#131 Assignee api
  back/src/controllers/assignee.controller.js
  back/src/middleware/assigneeValidator.js
  back/src/models/assignee.model.js
  back/src/routes/assignee.route.js
  back/src/routes/index.js
  back/src/services/assignee.service.js
Labels: API

#132 Get Issues
  back/src/controllers/issue.controller.js
  back/src/models/issue.model.js
  back/src/routes/index.js
  back/src/routes/issue.route.js
  back/src/services/issue.service.js
Labels: API

#144 Issue detail page
  front/src/components/AssigneesSelector.js
  front/src/components/CommentWriteSection.js
  front/src/pages/IssueDetailPage.js
  front/src/svgs/SettingSvg.js
Labels: 이슈 상세 화면

#145 Front issue list page
  front/src/components/IssueList.js
  front/src/components/SelectedCount.js
Labels: 이슈 목록 화면

#146 Fix Assignee Route
  back/src/routes/assignee.route.js
Labels: Bug

#147 front package.json and title
  front/index.html
  front/package.json
Labels: 환경 설정

#133 Create Issue
  back/src/controllers/issue.controller.js
  back/src/middleware/validateInputs.js
  back/src/models/issue.model.js
  back/src/routes/issue.route.js
  back/src/services/issue.service.js
Labels: API

#152 Add gitmessage.txt
  .gitmessage.txt
Labels: 환경 설정

#149 Login page design
  front/src/pages/LoginPage.js
  front/src/svgs/GitHubSvg.js
  front/src/svgs/PersonSvg.js
  front/src/svgs/SearchSvg.js
Labels: 로그인 페이지

#143 Rename variable name
  back/src/middleware/tokenValidator.js
Labels: API

#153 Sequelize Seeder
  back/package.json
  back/src/seeders/seeder.js
  back/src/sequelizeModels/relationship.sequelizeModel.js
Labels: 환경 설정

#142 Edit comment API
  back/src/controllers/comment.controller.js
  back/src/middleware/editCommentValidator.js
  back/src/models/comment.model.js
  back/src/routes/comment.route.js
  back/src/services/comment.service.js
Labels: API

#134 Delete comment API
  back/src/controllers/comment.controller.js
  back/src/middleware/deleteCommentValidator.js
  back/src/models/comment.model.js
  back/src/routes/comment.route.js
  back/src/services/comment.service.js
Labels: API

#161 Get comments
  back/src/controllers/comment.controller.js
  back/src/models/comment.model.js
  back/src/routes/comment.route.js
  back/src/services/comment.service.js
Labels: API

#163 Issue header
  front/src/components/IssuesHeader.js
Labels: 레이블 목록 화면

#162 CORS Middleware
  back/package-lock.json
  back/package.json
  back/src/app.js
Labels: 환경 설정

#151 Add github action for production
  .github/workflows/node.js.yml
  back/ecosystem.config.js
Labels: 환경 설정

#165 Refactor comment API
  back/src/controllers/comment.controller.js
  back/src/middleware/createCommentValidator.js
  back/src/routes/comment.route.js
  back/src/services/comment.service.js
Labels: API

#167 Add dotenv config to front
  front/.env.sample
  front/package-lock.json
  front/package.json
  front/webpack.config.js
Labels: 환경 설정

#164 Axios로 label api 호출해 label list 받아오기
  front/src/components/LabelFilterButton.js
  front/src/components/LabelsSelector.js
Labels: API, 이슈 목록 화면, 이슈 상세 화면

#168 Issue List Page (Get issue list, Rendering issue list)
  front/src/apis/issue.api.js
  front/src/components/IssueContent.js
  front/src/components/IssueInfo.js
  front/src/components/IssueList.js
Labels: 이슈 목록 화면

#160 Edit Issue
  back/src/controllers/issue.controller.js
  back/src/middleware/validateDatatypes.js
  back/src/middleware/validateInputs.js
  back/src/models/issue.model.js
  back/src/routes/issue.route.js
  back/src/services/issue.service.js
Labels: API

#174 Refactor Issue List Page
  front/src/components/IssueContent.js
  front/src/components/IssueList.js
  front/src/pages/IssueListPage.js
Labels: 이슈 목록 화면

#169 Oauth login
  back/package-lock.json
  back/package.json
  back/src/controllers/user.controller.js
  back/src/middleware/githubOauth.js
  back/src/middleware/tokenValidator.js
  back/src/models/user.model.js
  back/src/routes/index.js
  back/src/routes/user.route.js
  back/src/sequelizeModels/user.sequelizeModel.js
  back/src/services/user.service.js
Labels: API

#175 Get Issue Info and change some css
  front/src/components/AssigneesSelector.js
  front/src/components/CommentWriteSection.js
  front/src/components/IssueInfo.js
  front/src/components/IssueTitle.js
  front/src/components/LabelsSelector.js
  front/src/components/issueDetailContent.js
  front/src/pages/IssueDetailPage.js
Labels: API, 이슈 상세 화면

#177 Issue make Page
  front/src/apis/issue.api.js
  front/src/components/IssueWriteSection.js
  front/src/components/boxes/ProfileBox.js
  front/src/components/boxes/SpeechBox.js
  front/src/pages/IssueMakePage.js
Labels: 새로운 이슈 생성 화면

#181 IssueWriteSection Event, TextAreaBox
  front/src/components/IssueWriteSection.js
  front/src/components/boxes/TextAreaBox.js
  front/src/hooks/use.debounce.js
Labels: 새로운 이슈 생성 화면

#180 Apply Assignee Filter to IssueListPage
  front/src/components/AssigneeFilterButton.js
  front/src/components/AuthorFilterButton.js
  front/src/components/IssueContent.js
  front/src/components/IssueList.js
  front/src/pages/IssueListPage.js
  front/src/reducers/IssueListPageReducer.js
Labels: 이슈 목록 화면

#183 Add assignee avatar and milestone info to issue list page
  front/src/components/IssueContent.js
  front/src/components/IssueInfo.js
  front/src/svgs/MilestoneSvg.js
Labels: 이슈 목록 화면

#182 Create label modal
  front/src/apis/Labels.api.js
  front/src/components/LabelModal.js
  front/src/pages/LabelListPage.js
  front/src/svgs/RefreshSvg.js
Labels: 레이블 목록 화면

#185 Mark As (Change issue's Open Closed State)
  front/src/apis/issue.api.js
  front/src/components/IssueList.js
  front/src/components/MarkAs.js
  front/src/reducers/IssueListPageReducer.js
Labels: 이슈 목록 화면

#188 Issue make page
  front/src/apis/Labels.api.js
  front/src/components/AssigneesSelector.js
  front/src/components/IssueWriteSection.js
  front/src/components/LabelsSelector.js
  front/src/pages/IssueMakePage.js
Labels: 새로운 이슈 생성 화면

#189 Modify createIssue and editIssue API & Change sequelize config
  back/.env.sample
  back/src/models/issue.model.js
  back/src/sequelizeModels/config.sequelizeModels.js
Labels: API

#191 IssueHeader
  front/src/components/IssuesHeader.js
Labels: 이슈 목록 화면

#194 Build front package
  front/package-lock.json
  front/package.json
Labels: 환경 설정
